### ISSUE TITLE
Blood pressure monitor - no method for downloading the latest measurement

### ISSUE THREAD

**Issue by skadyrov** [ant-wireless/ANT-Android-SDKs#2]
I am trying to get measurement data during or right after the measurement of blood pressure. However, I do not want any old data also be received by my app. (Simply because it is hard to know whom these values belong to if there are multiple people using the same blood pressure monitor). 

I realized there is only one way to get data from the blood pressure monitor, that is:

```
AntPlusBloodPressurePcc.requestDownloadMeasurements(downloadNewOnly,
    monitorForNewMeasurements,
    downloadMeasurementStatusReceiver,
    measurementDownloadedReceiver,
    antFsProgressUpdateRecevier)
```

I tried setting `downloadNewOnly` to true, however the device is still transmitting more than one last data (if the previous ones were not transmitted before). Is there a way to receive only the single current measurement, like in Weight Scale devices? I also noticed that the latest measurement is received latest by the client. Is this always the case?

**Comment by ANT-Shane** [comment]
I put up some more info on https://www.thisisant.com/forum/viewthread/6356/. Let me know if you still have any questions.

Shane Gallup
Software Engineer E.I.T.

**Comment by skadyrov** [comment]
Thanks, that works! Didn't see that before.
