### ISSUE TITLE
is it possible to connect more than 8 devices with ant+ sdk?

### ISSUE THREAD

**Issue by RainThinks** [ant-wireless/ANT-Android-SDKs#7]
I am developing an Android app, which expected to read from up to 24 heart rate sensors synchronously with ant+ protocal, at least 1 sample/second from each sensor.

If I understood it correctly, only 8 channels available with single usb stick. So I'm wondering, if it is possible to extend channels by plug in second/third usb ant+ stick? Or is there other way to connect to so many sensors?

Any information would be greatly appreciated.

**Comment by ANT-Shane** [comment]
Best place to ask implementation questions is the ANT forum at https://www.thisisant.com/forum/.

For your use case the standard solution is to open a scan channel on a single ANT+ USB stick and parse the HR and device number from each message in your app. 
See https://www.thisisant.com/APIassets/Android_ANT_API/com/dsi/ant/channel/AntChannelProvider.html#acquireContinuousScanController(Context, com.dsi.ant.channel.AdapterInfo, com.dsi.ant.channel.PredefinedNetwork, boolean). 

Look on the thisisant website and forums for more info and app notes about using scan mode and 'group' environments.
